name: Vue.js CI/CD with Nginx
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: 
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH-deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USER}}
          password: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: |
            whoami
            cd /root/sfu-server
            git pull origin main
            npm install --force
            npm run build
            nginx -s reload
